version: '3'
services:
  webserver:
    image: draffle/airflow-server:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://airflow:airflow@mysql:3306/airflow
    links:
      - "mysql"
  mysql:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp=1
    environment:
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
      - "3306:3306"
