apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: draffle/airflow-server:latest
        ports:
        - name: airflow
          containerPort: 8080
        env:
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: mysql://airflow:airflow@<address of database-service>:30720/airflow
        livenessProbe:
          httpGet:
            path: /
            port: airflow
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: airflow
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: airflow
    protocol: TCP
  selector:
    app: airflow
  type: NodePort
