version: "3.3"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=postgres
      - DB_VENDOR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_PORT=5432

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_USER=keycloak
